all:
  vars:
    certbot_email: admin@nserd.ru
    openconnect_port: 1443

    root_dir: "{{ lookup('pipe', 'git rev-parse --show-toplevel') }}"
    files_dir: "{{ root_dir }}/files"

  hosts:
    example1.nserd.ru: { openconnect_port: 9000 }
    example2.nserd.ru: 
    example3.nserd.ru:
