all:
  vars:
    certbot_email: admin@nserd.ru
    
    root_dir: "{{ lookup('pipe', 'git rev-parse --show-toplevel') }}"
    files_dir: "{{ root_dir }}/files"
  hosts:
    vps.nserd.ru:
      ip: 45.80.71.65